Dev ag sp 11
SocialGouv/lebontuteur-app pull request #164
Opened 2019-02-08 14:32 UTC by gonzalezad1

2019-02-08 15:02 UTC, revolunet commented
le Layout Modal est spécifique au modales, ce serait bien de le nommer `ModalLayout.js` ou équivalent. 

(on a déjà `common/Layout.js` pour le layout de page)

2019-02-08 15:02 UTC, revolunet commented
prévoir de migrer tout ce qui est dans `components/communComponents` dans `components/common`

2019-02-08 15:05 UTC, revolunet requested changes

2019-02-08 15:05 UTC, revolunet commented on src/components/inscription/InscriptionIndividuel.js
> +    email: { type: "string", default: "" },
`format: "email"` ?

2019-02-08 15:05 UTC, revolunet commented on src/components/inscription/InscriptionTi.js
> +    email: { type: "string", title: "Adresse email", default: "" },
`format: "email"`

2019-02-08 15:05 UTC, revolunet commented on src/components/loginComponents/LoginForm.js
> +      <a href="/forgot-password">j&apos;ai oublié mon mot de passe et / où mon identifiant</a>
pas d'accent sur `où` ?

2019-02-08 15:05 UTC, revolunet commented on src/components/tiComponents/actions/mesures.js
> +  apiFetch(`/mandataires/1/mesures/${data.id}`, {
normal que le ti tape sur le endPoint mandataire ?

2019-02-08 15:24 UTC, gonzalezad1 commented on src/components/inscription/InscriptionIndividuel.js
> +    email: { type: "string", default: "" },
C'est dans le uiSchema...

2019-02-08 15:24 UTC, gonzalezad1 commented on src/components/inscription/InscriptionTi.js
> +    email: { type: "string", title: "Adresse email", default: "" },
C'est dans le uiSchema...

2019-02-08 15:24 UTC, gonzalezad1 commented on src/components/tiComponents/actions/mesures.js
> +  apiFetch(`/mandataires/1/mesures/${data.id}`, {
C'est une mesure de mandataire que l'on change...

2019-02-08 15:39 UTC, revolunet commented on src/components/inscription/InscriptionIndividuel.js
> +    email: { type: "string", default: "" },
je pense qu'il faut mieux le mettre dans le schema lui-même car `format` c'est bien dans la [spec JSONSchema](https://json-schema.org/understanding-json-schema/reference/string.html#format) pour les strings, et dans [la doc pour le schema de react-jsonschema-form](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#string-formats).

2019-02-12 09:54 UTC, revolunet approved these changes

2019-02-12 09:55 UTC, merged